implementations:
  baseline:
    github: mruby/mruby
    revision: 8455344bf3fd92ca00f598accfe6b3eb29ddcb0c
#    path: ../mruby
#    revision: master
  new:
    github: shuujii/mruby
    revision: f2d8db39be487fcd710c5c5844ae47d3a6920e70
#    path: ../mruby
#    revision: reduce-memory-usage-of-Hash-object
